version: "3.6"

services:
  backend:
    image: ${DOCKER_REGISTRY}/n2o-components/rdm/backend:${TAG}

  frontend:
    image: ${DOCKER_REGISTRY}/n2o-components/rdm/frontend:${TAG}

  esnsi:
    image: ${DOCKER_REGISTRY}/n2o-components/rdm/esnsi:${TAG}

  db:
    image: ${DOCKER_REGISTRY}/n2o-components/rdm/db:${TAG}

